name: Simple CI/CD for Java Application

on: 
  push:
    branches:
      - "master"
  workflow_dispatch:
    
jobs: 
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Get code
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
        name: Setup java
      - run: ./mvnw clean verify
        name: Run java tests
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        name: SonarCloud Scan