name: Simple CI/CD for Java Application

on: 
  push:
    branches:
      - "master"


jobs: 
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Get code
      - uses: actions/checkout@v3
        with:
          java-version: '17'
        name: Setup java
      - run: ./mvnw clean verify
        name: Run java tests