name: Simple CI/CD for Java Application

env:
  SONAR_PROJECT_KEY: georgemore00_github-actions-spring-boot

on: 
  push:
    branches:
      - "master"
  workflow_dispatch:
    
jobs: 
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Get code
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
        name: Setup java
      - run: ./mvnw clean verify
        name: Run java tests
      - run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        name: Sonarcloud scan
        