name: Simple CI/CD for Java Application

env:
  SONAR_PROJECT_KEY: georgemore00_github-actions-spring-boot

on: 
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs: 
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup java  
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Cache SonarQube Packages
        uses: actions/cache@v1
        with: 
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Run java tests    
        run: ./mvnw clean verify
      - name: list directories
        run: ls
      - name: SonarQube scan  
        run: mvn sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/app:latest